#!/bin/bash
command -v instabrute > /dev/null 2>&1 || { echo >&2 "Updating instabrute...."; rm $PREFIX/bin/instabrute ; rm $PREFIX/bin/anonps ; rm $PREFIX/bin/cupp.cfg ; }
command -v python > /dev/null 2>&1 || { echo >&2 "python not found !, Installing... python"; pkg install python -y 1; }
command -v figlet > /dev/null 2>&1 || { echo >&2 "figlet not found !, Installing... figlet"; pkg install figlet -y 1; }
command -v tor > /dev/null 2>&1 || { echo >&2 "tor not found !, Installing... tor"; pkg install tor -y 1; }
command -v toilet > /dev/null 2>&1 || { echo >&2 "toilet not found !, Installing... toilet"; pkg install toilet -y 1; }
figlet setup
pip install stem > /dev/null 2>&1
pip install instagram-py > /dev/null 2>&1
instagram-py -cc -dc > /dev/null 2>&1
curl -LO https://raw.githubusercontent.com/Anon4You/InstaBrute/main/anonps 
curl -LO https://raw.githubusercontent.com/Anon4You/InstaBrute/main/cupp.cfg 
curl -LO https://raw.githubusercontent.com/Anon4You/InstaBrute/main/instabrute 
mv instabrute $PREFIX/bin
mv anonps $PREFIX/bin
mv cupp.cfg $PREFIX/bin
chmod +x $PREFIX/bin/instabrute
chmod +x $PREFIX/bin/anonps
chmod +x $PREFIX/bin/cupp.cfg
curl -LO https://raw.githubusercontent.com/Python-Fa/Password-List/master/Password-List.txt 
mv Password-List.txt .pss
clear
figlet Installed
echo""
echo "Now type "$'\e[32;1m'"instabrute"$'\e[0m'" to run the tool"
